/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaApp1;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App1 classUnderTest = new App1();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
